enum PageType {
  EVENT = 'EVENT',
  TAG = 'TAG',
  PRIVATE_BOOKING = 'PRIVATE_BOOKING',
  TRAVEL_PASS = 'TRAVEL_PASS',
  RECURRING_PRODUCT = 'RECURRING_PRODUCT', // also BOOKED && JUST_BOARD
  PRIVATE_HIRE_CONTENT = 'PRIVATE_HIRE_CONTENT',
}

export default PageType;
