enum ServiceType {
  TAXI = 'TAXI',
  SCHOOL_BUS = 'SCHOOL_BUS',
  MEDICAID = 'MEDICAID',
  TRANSIT = 'TRANSIT',
  CHARTER = 'CHARTER',
  LIMO = 'LIMO',
  CORPORATE_SHUTTLE = 'CORPORATE_SHUTTLE',
  UNIVERSITY_SHUTTLE = 'UNIVERSITY_SHUTTLE',
}

export default ServiceType;
