enum SupplyCostLogType {
  TRIP_CREATED = 'TRIP_CREATED',
  MANUAL_NOTE = 'MANUAL_NOTE',
  CLIENT_FEE_CHANGE = 'CLIENT_FEE_CHANGE',
  SUPPLY_COST_CHANGE = 'SUPPLY_COST_CHANGE',
  NEW_VERSION = 'NEW_VERSION',
}

export default SupplyCostLogType;
