enum Permission {
  SUPPLIER_SUPER_ADMIN = 'SUPPLIER_SUPER_ADMIN',

  ZEELO_LIVE = 'ZEELO_LIVE_ACCESS',

  PASSENGER_TYPES = 'PASSENGER_TYPE_ACCESS',
  PASSENGER_TYPES_SHOW = 'PASSENGER_TYPE_SHOW',
  PASSENGER_TYPES_CREATE = 'PASSENGER_TYPE_CREATE',
  PASSENGER_TYPES_UPDATE = 'PASSENGER_TYPE_UPDATE',
  PASSENGER_TYPES_DISABLE = 'PASSENGER_TYPE_DISABLE',

  STOPS = 'STOP_ACCESS',
  STOPS_CREATE = 'STOP_CREATE',
  STOPS_SHOW = 'STOP_SHOW',
  STOPS_UPDATE = 'STOP_UPDATE',
  STOPS_DISABLE = 'STOP_DISABLE',

  ROUTES = 'ROUTE_ACCESS',
  ROUTES_CREATE = 'ROUTE_CREATE',
  ROUTES_SHOW = 'ROUTE_SHOW',
  ROUTES_UPDATE = 'ROUTE_UPDATE',
  ROUTES_DISABLE = 'ROUTE_DISABLE',

  JOURNEYS = 'JOURNEY_ACCESS',
  JOURNEYS_SHOW = 'JOURNEY_SHOW',
  JOURNEYS_SUPPLIER_SHOW = 'JOURNEY_SUPPLIER_SHOW',
  JOURNEYS_DISABLE = 'JOURNEY_DISABLE',
  JOURNEYS_CREATE = 'JOURNEY_CREATE',
  JOURNEYS_UPDATE = 'JOURNEY_UPDATE',
  JOURNEY_VEHICLES_SHOW = 'JOURNEY_VEHICLE_SHOW',
  JOURNEY_VEHICLES_UPDATE = 'VEHICLE_UPDATE',
  JOURNEY_VEHICLES_TRACKING = 'JOURNEY_VEHICLE_TRACKING',
  JOURNEY_VEHICLES_MANAGE_PASSENGERS = 'JOURNEY_VEHICLE_ALLOCATE_ACCESS',
  JOURNEY_VEHICLES_MANAGE_PASSENGERS_ALLOCATE = 'JOURNEY_VEHICLE_ALLOCATE_PASSENGERS',
  JOURNEY_VEHICLE_NOTES_CREATE = 'JOURNEY_VEHICLE_NOTES_CREATE',
  JOURNEY_VEHICLE_NOTES_DISABLE = 'JOURNEY_VEHICLE_NOTES_DISABLE', // Not being used yet but it will be.
  JOURNEY_VEHICLE_MESSAGES_SEND = 'JOURNEY_VEHICLE_MESSAGE_SEND',
  JOURNEY_VEHICLES_UPDATE_STATUS = 'JOURNEY_VEHICLE_UPDATE_STATUS',
  JOURNEY_VEHICLES_METRICS_SHOW = 'JOURNEY_VEHICLE_METRICS_SHOW',
  JOURNEY_VEHICLES_GRADING_SHOW = 'JOURNEY_VEHICLE_GRADING_SHOW',
  JOURNEY_VEHICLES_COSTS_SHOW = 'JOURNEY_VEHICLE_COSTS_SHOW',
  JOURNEY_VEHICLES_COSTS_UPDATE = 'JOURNEY_VEHICLE_COSTS_UPDATE',
  // SERVICE_FEES_SUPPLY_COSTS = 'SERVICE_FEES_SUPPLY_COSTS_ACCESS', // Deprecated.

  PRODUCTS = 'PRODUCT_ACCESS',
  PRODUCTS_SHOW = 'PRODUCTS_SHOW',

  EVENTS_CREATE = 'EVENT_CREATE',
  EVENTS_SHOW = 'EVENT_SHOW',
  EVENTS_UPDATE = 'EVENT_UPDATE',
  EVENTS_DISABLE = 'EVENT_DISABLE',

  PRIVATE_BOOKINGS_CREATE = 'PRIVATE_BOOKING_CREATE',
  PRIVATE_BOOKINGS_SHOW = 'PRIVATE_BOOKING_SHOW',
  PRIVATE_BOOKINGS_UPDATE = 'PRIVATE_BOOKING_UPDATE',
  PRIVATE_BOOKINGS_DISABLE = 'PRIVATE_BOOKING_DISABLE',

  PRIVATE_HIRE = 'PRIVATE_HIRE_ACCESS',
  PRIVATE_HIRE_CREATE = 'PRIVATE_HIRE_CREATE',
  PRIVATE_HIRE_SHOW = 'PRIVATE_HIRE_SHOW',
  PRIVATE_HIRE_UPDATE = 'PRIVATE_HIRE_UPDATE',
  PRIVATE_HIRE_DISABLE = 'PRIVATE_HIRE_DISABLE',

  RECURRING_PRODUCTS_CREATE = 'RECURRING_PRODUCT_CREATE',
  RECURRING_PRODUCTS_SHOW = 'RECURRING_PRODUCT_SHOW',
  RECURRING_PRODUCTS_UPDATE = 'RECURRING_PRODUCT_UPDATE',
  RECURRING_PRODUCTS_DISABLE = 'RECURRING_PRODUCT_DISABLE',

  TRAVEL_PASSES_ACCESS = 'TRAVEL_PASS_ACCESS',
  TRAVEL_PASSES_CREATE = 'TRAVEL_PASS_CREATE',
  TRAVEL_PASSES_SHOW = 'TRAVEL_PASS_SHOW',
  TRAVEL_PASSES_UPDATE = 'TRAVEL_PASS_UPDATE',
  TRAVEL_PASSES_DISABLE = 'TRAVEL_PASS_DISABLE',

  SUPPLIERS = 'SUPPLIER_ACCESS',
  SUPPLIERS_SHOW = 'SUPPLIER_SHOW',
  SUPPLIERS_CREATE = 'SUPPLIER_CREATE',
  SUPPLIERS_UPDATE = 'SUPPLIER_UPDATE',
  SUPPLIERS_DISABLE = 'SUPPLIER_DISABLE',

  SUPPLIERS_INTERNAL_NOTES_ACCESS = 'SUPPLIER_INTERNAL_NOTES_ACCESS',

  VEHICLES = 'VEHICLE_ACCESS',
  VEHICLES_CREATE = 'VEHICLE_CREATE',
  VEHICLES_SHOW = 'VEHICLE_SHOW',
  VEHICLES_UPDATE = 'VEHICLE_UPDATE',
  VEHICLES_DISABLE = 'VEHICLE_DISABLE',

  DRIVERS = 'DRIVER_ACCESS',
  DRIVERS_CREATE = 'DRIVER_CREATE',
  DRIVERS_SHOW = 'DRIVER_SHOW',
  DRIVERS_UPDATE = 'DRIVER_UPDATE',
  DRIVERS_DISABLE = 'DRIVER_DISABLE',

  IMAGES_CREATE = 'IMAGE_CREATE',
  IMAGES_DISABLE = 'IMAGE_DISABLE',

  PROMO_CODES = 'PROMO_ACCESS',
  PROMO_CODES_CREATE = 'PROMO_CREATE',
  PROMO_CODES_SHOW = 'PROMO_SHOW',
  PROMO_CODES_UPDATE = 'PROMO_UPDATE',
  PROMO_CODES_DISABLE = 'PROMO_DISABLE',

  TAGS = 'TAG_ACCESS',
  TAGS_CREATE = 'TAG_CREATE',
  TAGS_SHOW = 'TAG_SHOW',
  TAGS_UPDATE = 'TAG_UPDATE',
  TAGS_DISABLE = 'TAG_DISABLE',

  DATA_LABELS = 'DATA_LABEL_ACCESS',
  DATA_LABELS_CREATE = 'DATA_LABEL_CREATE',
  DATA_LABELS_SHOW = 'DATA_LABEL_SHOW',
  DATA_LABELS_UPDATE = 'DATA_LABEL_UPDATE',
  DATA_LABELS_DISABLE = 'DATA_LABEL_DISABLE',

  PAYMENTS = 'PAYMENT_ACCESS',
  PAYMENTS_SHOW = 'PAYMENT_SHOW',
  PAYMENTS_CAPTURE = 'PAYMENT_CAPTURE',
  PAYMENTS_RELEASE = 'PAYMENT_RELEASE',
  PAYMENTS_REFUND = 'PAYMENT_REFUND',

  REVIEW = 'REVIEW_ACCESS',

  ALLOCATIONS = 'ALLOCATION_ACCESS',
  ALLOCATIONS_UPDATE_TRAVEL_DETAILS = 'ALLOCATIONS_UPDATE', // Allocations Update Driver/Vehicle/Phone,
  ALLOCATIONS_UPDATE_SUPPLIER = 'ALLOCATION_UPDATE_SUPPLIER',

  OPERATOR_UPDATE = 'OPERATOR_UPDATE',

  USERS = 'USER_ACCESS',
  USERS_UPLOAD = 'USER_UPLOAD',
  USERS_SHOW = 'USER_SHOW',
  USERS_UPDATE = 'USER_UPDATE',
  USERS_DISABLE = 'USER_DISABLE',
  USERS_IMPERSONATE = 'USER_IMPERSONATE',
  USERS_MFA_STATUS_SHOW = 'USERS_MFA_STATUS_SHOW',
  USERS_MFA_ENABLE = 'USER_MFA_ENABLE',
  USERS_MFA_DISABLE = 'USER_MFA_DISABLE',
  USERS_REVEAL_ACTIVE_OTP = 'USER_REVEAL_OTP',
  USERS_VERIFY_PHONE_NUMBER = 'USER_VERIFY_PHONE_NUMBER',
  USERS_REVOKE_ACCESS_TOKEN = 'USER_REVOKE_ACCESS_TOKEN',

  PRODUCT_PURCHASE_STOPS_UPDATE = 'PRODUCT_PURCHASE_STOPS_UPDATE',
  PRODUCT_PURCHASE_CREDITS_UPDATE = 'USER_UPDATE_CREDITS',
  PRODUCT_PURCHASE_UNPURCHASE = 'PRODUCT_PURCHASE_UNPURCHASE',
  PRODUCT_PURCHASE_AUTO_TOP_UP_DISABLE = 'PRODUCT_PURCHASE_AUTO_TOP_UP_DISABLE',
  AUTO_TOP_UP_DISABLE = 'DISABLE_AUTO_TOPUP',

  USERS_FOLLOWERS_SHOW = 'USER_FOLLOWER_SHOW',
  USERS_FOLLOWERS_CREATE = 'USER_FOLLOWER_CREATE',
  USERS_FOLLOWERS_DISABLE = 'USER_FOLLOWER_DISABLE',

  USERS_LINKED_RIDERS_SHOW = 'USER_LINKED_RIDER_SHOW',
  USERS_LINKED_RIDERS_CREATE = 'USER_LINKED_RIDER_CREATE',
  USERS_LINKED_RIDERS_UPDATE = 'USER_LINKED_RIDER_UPDATE',

  ME_SHOW = 'ME_SHOW',
  ME_UPDATE = 'ME_UPDATE',

  MY_BUSINESS_SHOW = 'MY_BUSINESS_SHOW',
  MY_BUSINESS_UPDATE = 'MY_BUSINESS_UPDATE',

  BUSINESS_LIST = 'BUSINESS_LIST_ACCESS',
  BUSINESS_UPDATE = 'BUSINESS_EDIT_ACCESS',
  BUSINESS_USER_EDIT = 'BUSINESS_USER_EDIT',
  BUSINESS_USER_DELETE = 'BUSINESS_USER_DELETE',

  SEND_NOTIFICATIONS = 'SEND_NOTIFICATION',

  BUSINESS_ZEERIDE_PLAN_SHOW = 'BUSINESS_ZEERIDE_PLAN_SHOW',

  MC_USER_UPDATE = 'MC_USER_UPDATE',
  MC_USER_SHOW = 'MC_USER_SHOW',

  PHONE_NUMBER_VERIFICATION_CODE_SHOW = 'PHONE_NUMBER_VERIFICATION_CODE_SHOW',

  // GENERAL PERMISSIONS
  OPERATOR_CREATE = 'OPERATOR_CREATE',
  OPERATOR_DISABLE = 'OPERATOR_DISABLE',

  TRACKER_ROLE_UPDATE = 'TRACKER_ROLE_UPDATE',

  SUPPLY_COSTS_SHOW = 'SUPPLY_COSTS_SHOW',
  SUPPLY_COSTS_EDIT = 'SUPPLY_COSTS_EDIT',
}

export default Permission;
