enum RoleScopeType {
  REGULAR_USER = 'REGULAR_USER',
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  TRACKER = 'TRACKER',
  DEVELOPER = 'DEVELOPER',
  IMPERSONATOR = 'IMPERSONATOR',
  OPERATOR = 'OPERATOR_ADMIN',
  RINA_USER = 'RINA_USER',
}

export default RoleScopeType;
