enum JourneyVehicleActivityType {
  DRIVER_NOT_LOGGED_IN = 'DRIVER_NOT_LOGGED_IN',
  DRIVER_STARTED_JOURNEY = 'DRIVER_STARTED_JOURNEY',
  NOT_ARRIVED_AT_FIRST_STOP_BEFORE_SCHEDULE = 'NOT_ARRIVED_FIRST_STOP',
  ARRIVED_AT_STOP_BEHIND_SCHEDULE = 'ARRIVED_AT_STOP_BEHIND_SCHEDULED',
  DEPARTED_FROM_STOP_AHEAD_SCHEDULE = 'DEPARTED_FROM_STOP_AHEAD_SCHEDULED',
  DEPARTED_FROM_STOP_BEHIND_SCHEDULE = 'DEPARTED_STOP_BEHID_SCHEDULED',
  PASSENGERS_NOT_BOARDED = 'PASSENGERS_NOT_BOARDED',
  INTERNAL_NOTE = 'INTERNAL_NOTE',
  MANUAL_ISSUE = 'MANUAL_ISSUE',
  NEW_DRIVER = 'NEW_DRIVER',
  MUTED_NOTIFICATIONS = 'MUTED',
  UNMUTED_NOTIFICATIONS = 'UNMUTED',
  FOLLOWER_NOTIFICATIONS_ENABLED = 'FOLLOWER_NOTIFICATIONS_ENABLED',
  FOLLOWER_NOTIFICATIONS_DISABLED = 'FOLLOWER_NOTIFICATIONS_DISABLED',
  RESOLVED_ISSUES = 'RESOLVED',
  EXPECTED_DELAY = 'EXPECTED_DELAY',
  DRIVER_NOT_LOGGED_IN_NOTIFICATION_SENT = 'DRIVER_NOT_LOGGED_IN_NOTIFICATION_SENT',
  DRIVER_NOT_LOGGED_IN_AFTER_SMS_SENT = 'DRIVER_NOT_LOGGED_IN_AFTER_SMS_SENT',
}

export default JourneyVehicleActivityType;
